"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowDown, ArrowLeft, ArrowUp, Loader2, Plus, Save, Send, Trash2 } from "lucide-react";
import { PlanRiskLevel, ResourceRequestType } from "@prisma/client";
import { createMonthlyPlanDraft, publishMonthlyPlan, updateMonthlyPlanDraft } from "@/actions/monthly-plans";
import { planRiskLevelLabels, resourceRequestTypeLabels } from "@/lib/plans/dictionaries";
import type { MonthlyPlanInput } from "@/lib/validations/monthly-plans";

type InitialData = MonthlyPlanInput & { id: string };
type SectionKey = Exclude<keyof MonthlyPlanInput, "productLineTeamId" | "year" | "month">;
type Column<T> = { field: keyof T; label: string; type?: "date" | "select"; options?: Record<string, string>; optional?: boolean };
const inputClass="w-full min-w-40 rounded border border-border bg-input px-2 py-2 text-xs text-white focus:border-emerald-500 focus:outline-none";
const labels: Record<SectionKey,string>={productDeliveries:"一、产品交付计划",projectDeliveries:"二、项目交付计划",marketActions:"三、市场化动作计划",costOptimizations:"四、成本优化计划",aiProductEnablements:"五、AI+赋能产品计划",aiEfficiencies:"六、AI+效能提升计划",risks:"七、项目风险",resourceRequests:"八、资源需求"};

export default function MonthlyPlanForm({teams,initialData}:{teams:Array<{id:string;name:string}>;initialData?:InitialData}){
 const router=useRouter();const [pending,startTransition]=useTransition();const now=new Date();
 const [teamId,setTeamId]=useState(initialData?.productLineTeamId??(teams.length===1?teams[0].id:""));
 const [period,setPeriod]=useState(`${initialData?.year??now.getFullYear()}-${String(initialData?.month??now.getMonth()+1).padStart(2,"0")}`);
 const [sections,setSections]=useState({productDeliveries:initialData?.productDeliveries??[],projectDeliveries:initialData?.projectDeliveries??[],marketActions:initialData?.marketActions??[],costOptimizations:initialData?.costOptimizations??[],aiProductEnablements:initialData?.aiProductEnablements??[],aiEfficiencies:initialData?.aiEfficiencies??[],risks:initialData?.risks??[],resourceRequests:initialData?.resourceRequests??[]});
 const [error,setError]=useState("");const [year,month]=period.split("-").map(Number);
 const setRows=<K extends SectionKey>(section:K,rows:MonthlyPlanInput[K])=>setSections((current)=>({...current,[section]:rows}));
 const payload=():MonthlyPlanInput=>({productLineTeamId:teamId,year,month,...sections});
 const submit=(publish:boolean)=>{setError("");startTransition(async()=>{const result=publish?await publishMonthlyPlan(initialData?.id??null,payload()):initialData?await updateMonthlyPlanDraft(initialData.id,payload()):await createMonthlyPlanDraft(payload());if(!result.success)return setError(result.error??"保存失败");router.push(`/plans/monthly/${result.data?.id??initialData?.id}`);router.refresh()})};
 const actions=<div className="flex flex-wrap justify-end gap-3"><Link href="/plans?tab=monthly" className="rounded-lg border border-border px-4 py-2 text-sm"><ArrowLeft className="mr-1 inline h-4 w-4"/>返回列表</Link><button disabled={pending} onClick={()=>submit(false)} className="rounded-lg border border-amber-500/40 px-4 py-2 text-sm text-amber-300"><Save className="mr-1 inline h-4 w-4"/>保存为草稿</button><button disabled={pending} onClick={()=>submit(true)} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm text-white">{pending?<Loader2 className="mr-1 inline h-4 w-4 animate-spin"/>:<Send className="mr-1 inline h-4 w-4"/>}制定并发布</button></div>;
 return <div className="space-y-6">{actions}{error&&<div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}<div className="glass grid gap-4 rounded-xl p-5 md:grid-cols-2"><label className="text-xs text-muted-foreground">产品线小组 *<select value={teamId} onChange={(e)=>setTeamId(e.target.value)} className={inputClass}><option value="">请选择</option>{teams.map((team)=><option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label className="text-xs text-muted-foreground">计划月份 *<input type="month" value={period} onChange={(e)=>setPeriod(e.target.value)} className={inputClass}/></label></div>
 <EditableSection title={labels.productDeliveries} rows={sections.productDeliveries} setRows={(rows)=>setRows("productDeliveries",rows)} blank={{moduleVersion:"",deliveryContent:"",plannedCompletionDate:""}} columns={[{field:"moduleVersion",label:"模块/功能/版本"},{field:"deliveryContent",label:"交付内容（必须有书面记录）"},{field:"plannedCompletionDate",label:"计划完成时间",type:"date"}]}/>
 <EditableSection title={labels.projectDeliveries} rows={sections.projectDeliveries} setRows={(rows)=>setRows("projectDeliveries",rows)} blank={{projectName:"",deliveryContent:"",plannedCompletionDate:"",customerName:""}} columns={[{field:"projectName",label:"项目名称"},{field:"deliveryContent",label:"交付内容（必须有书面记录）"},{field:"plannedCompletionDate",label:"计划完成时间",type:"date"},{field:"customerName",label:"客户名称",optional:true}]}/>
 <EditableSection title={labels.marketActions} rows={sections.marketActions} setRows={(rows)=>setRows("marketActions",rows)} blank={{productOrProject:"",marketAction:"",outputResult:"",plannedCompletionDate:""}} columns={[{field:"productOrProject",label:"产品/项目"},{field:"marketAction",label:"市场化动作"},{field:"outputResult",label:"输出成果（书面记录）"},{field:"plannedCompletionDate",label:"计划完成时间",type:"date"}]}/>
 <EditableSection title={labels.costOptimizations} rows={sections.costOptimizations} setRows={(rows)=>setRows("costOptimizations",rows)} blank={{optimizationItem:"",currentProblem:"",optimizationMeasure:""}} columns={[{field:"optimizationItem",label:"优化项"},{field:"currentProblem",label:"当前问题"},{field:"optimizationMeasure",label:"优化措施"}]}/>
 <EditableSection title={labels.aiProductEnablements} rows={sections.aiProductEnablements} setRows={(rows)=>setRows("aiProductEnablements",rows)} blank={{item:"",outputResult:"",plannedCompletionDate:""}} columns={[{field:"item",label:"事项"},{field:"outputResult",label:"输出成果（书面记录）"},{field:"plannedCompletionDate",label:"计划完成时间",type:"date"}]}/>
 <EditableSection title={labels.aiEfficiencies} rows={sections.aiEfficiencies} setRows={(rows)=>setRows("aiEfficiencies",rows)} blank={{item:"",outputResult:"",plannedCompletionDate:""}} columns={[{field:"item",label:"事项"},{field:"outputResult",label:"输出成果（书面记录）"},{field:"plannedCompletionDate",label:"计划完成时间",type:"date"}]}/>
 <EditableSection title={labels.risks} rows={sections.risks} setRows={(rows)=>setRows("risks",rows)} blank={{riskItem:"",riskLevel:PlanRiskLevel.MEDIUM,impactScope:"",responseMeasure:""}} columns={[{field:"riskItem",label:"风险项"},{field:"riskLevel",label:"风险等级",type:"select",options:planRiskLevelLabels},{field:"impactScope",label:"影响范围"},{field:"responseMeasure",label:"应对措施"}]}/>
 <EditableSection title={labels.resourceRequests} rows={sections.resourceRequests} setRows={(rows)=>setRows("resourceRequests",rows)} blank={{requestType:ResourceRequestType.PEOPLE,content:"",urgency:PlanRiskLevel.MEDIUM,supportDepartment:""}} columns={[{field:"requestType",label:"需求类型",type:"select",options:resourceRequestTypeLabels},{field:"content",label:"具体内容"},{field:"urgency",label:"紧急程度",type:"select",options:planRiskLevelLabels},{field:"supportDepartment",label:"需要支持部门/小组"}]}/>{actions}</div>
}

function EditableSection<T extends object>({title,rows,setRows,blank,columns}:{title:string;rows:T[];setRows:(rows:T[])=>void;blank:T;columns:Array<Column<T>>}){
 const move=(index:number,direction:-1|1)=>{const target=index+direction;if(target<0||target>=rows.length)return;const next=[...rows];[next[index],next[target]]=[next[target],next[index]];setRows(next)};
 return <section className="space-y-3 rounded-xl border border-border p-4"><div className="flex items-center justify-between"><h2 className="font-semibold text-emerald-300">{title}</h2><button onClick={()=>setRows([...rows,{...blank}])} className="rounded-lg border border-emerald-500/40 px-3 py-2 text-xs text-emerald-300"><Plus className="mr-1 inline h-3.5 w-3.5"/>新增行</button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-xs"><thead className="bg-white/5"><tr>{columns.map((column)=><th key={String(column.field)} className="p-2 text-left">{column.label}{!column.optional&&" *"}</th>)}<th className="p-2">操作</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={columns.length+1} className="p-6 text-center text-muted-foreground">暂无数据</td></tr>:rows.map((row,index)=><tr key={index} className="border-t border-border">{columns.map((column)=>{const value=row[column.field];return <td key={String(column.field)} className="p-2">{column.type==="select"?<select value={String(value??"")} onChange={(e)=>setRows(rows.map((current,i)=>i===index?{...current,[column.field]:e.target.value}:current))} className={inputClass}>{Object.entries(column.options??{}).map(([option,label])=><option key={option} value={option}>{label}</option>)}</select>:column.type==="date"?<input type="date" value={String(value??"")} onChange={(e)=>setRows(rows.map((current,i)=>i===index?{...current,[column.field]:e.target.value}:current))} className={inputClass}/>:<textarea value={String(value??"")} onChange={(e)=>setRows(rows.map((current,i)=>i===index?{...current,[column.field]:e.target.value}:current))} className={`${inputClass} min-h-16 resize-y`}/>}</td>})}<td className="p-2"><div className="flex gap-2"><button onClick={()=>move(index,-1)}><ArrowUp className="h-4 w-4"/></button><button onClick={()=>move(index,1)}><ArrowDown className="h-4 w-4"/></button><button onClick={()=>setRows(rows.filter((_,i)=>i!==index))} className="text-rose-400"><Trash2 className="h-4 w-4"/></button></div></td></tr>)}</tbody></table></div></section>
}
