"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { ArrowDown, ArrowLeft, ArrowUp, Loader2, Plus, Save, Send, Trash2 } from "lucide-react";
import { PlanRiskLevel, PlanTrackingStatus, QuarterlyGoalDomain, QuarterlyRiskStatus } from "@prisma/client";
import { createQuarterlyPlanDraft, publishQuarterlyPlan, updateQuarterlyPlanDraft } from "@/actions/quarterly-plans";
import { planRiskLevelLabels, planTrackingStatusLabels, quarterlyGoalDomainLabels, quarterlyRiskStatusLabels } from "@/lib/plans/dictionaries";
import type { QuarterlyPlanInput } from "@/lib/validations/quarterly-plans";

type Goal = QuarterlyPlanInput["goals"][number] & { _key: string };
type Risk = QuarterlyPlanInput["risks"][number] & { _key: string };
type InitialData = QuarterlyPlanInput & { id: string };
const makeKey = () => crypto.randomUUID();
const inputClass = "w-full min-w-36 rounded border border-border bg-input px-2 py-2 text-xs text-white focus:border-indigo-500 focus:outline-none";
const textAreaClass = `${inputClass} min-h-20 resize-y`;

const blankGoal = (): Goal => ({ _key: makeKey(), domain: null, quarterlyGoal: "", successCriteria: "", month1Goal: "", month1Status: PlanTrackingStatus.NOT_STARTED, month2Goal: "", month2Status: PlanTrackingStatus.NOT_STARTED, month3Goal: "", month3Status: PlanTrackingStatus.NOT_STARTED, currentCompletion: "", achievementRate: 0, quarterlyStatus: PlanTrackingStatus.NOT_STARTED, keyDependencies: "", notes: "" });
const blankRisk = (): Risk => ({ _key: makeKey(), riskDescription: "", affectedMilestone: "", probability: PlanRiskLevel.MEDIUM, impact: PlanRiskLevel.MEDIUM, overallLevel: PlanRiskLevel.MEDIUM, triggerCondition: "", responseStrategy: "", warningPoint: "", status: QuarterlyRiskStatus.NOT_TRIGGERED });
const withoutKey = <T extends { _key: string }>(row: T): Omit<T, "_key"> => { const copy = { ...row }; delete (copy as Partial<T>)._key; return copy; };

export default function QuarterlyPlanForm({ teams, initialData }: { teams: Array<{ id: string; name: string }>; initialData?: InitialData }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [teamId, setTeamId] = useState(initialData?.productLineTeamId ?? (teams.length === 1 ? teams[0].id : ""));
  const [year, setYear] = useState(initialData?.year ?? new Date().getFullYear());
  const [quarter, setQuarter] = useState(initialData?.quarter ?? Math.ceil((new Date().getMonth() + 1) / 3));
  const [goals, setGoals] = useState<Goal[]>(initialData?.goals.map((row) => ({ ...row, _key: makeKey() })) ?? [blankGoal()]);
  const [risks, setRisks] = useState<Risk[]>(initialData?.risks.map((row) => ({ ...row, _key: makeKey() })) ?? []);
  const [error, setError] = useState("");
  const months = [quarter * 3 - 2, quarter * 3 - 1, quarter * 3];
  const move = <T,>(rows: T[], index: number, direction: -1 | 1) => { const next = [...rows]; const target = index + direction; if (target < 0 || target >= rows.length) return rows; [next[index], next[target]] = [next[target], next[index]]; return next; };
  const payload = (): QuarterlyPlanInput => ({ productLineTeamId: teamId, year, quarter, goals: goals.map(withoutKey), risks: risks.map(withoutKey) });
  const submit = (publish: boolean) => { setError(""); startTransition(async () => { const result = publish ? await publishQuarterlyPlan(initialData?.id ?? null, payload()) : initialData ? await updateQuarterlyPlanDraft(initialData.id, payload()) : await createQuarterlyPlanDraft(payload()); if (!result.success) { setError(result.error ?? "保存失败"); return; } router.push(`/plans/quarterly/${result.data?.id ?? initialData?.id}`); router.refresh(); }); };
  const actions = <div className="flex flex-wrap justify-end gap-3"><Link href="/plans?tab=quarterly" className="rounded-lg border border-border px-4 py-2 text-sm"><ArrowLeft className="mr-1 inline h-4 w-4" />返回列表</Link><button type="button" disabled={pending} onClick={() => submit(false)} className="rounded-lg border border-amber-500/40 px-4 py-2 text-sm text-amber-300"><Save className="mr-1 inline h-4 w-4" />保存为草稿</button><button type="button" disabled={pending} onClick={() => submit(true)} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white">{pending ? <Loader2 className="mr-1 inline h-4 w-4 animate-spin" /> : <Send className="mr-1 inline h-4 w-4" />}制定并发布</button></div>;

  return <div className="space-y-6">{actions}{error && <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}
    <div className="glass grid gap-4 rounded-xl p-5 md:grid-cols-3"><label className="text-xs text-muted-foreground">产品线小组 *<select value={teamId} onChange={(e) => setTeamId(e.target.value)} className={inputClass}><option value="">请选择</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label className="text-xs text-muted-foreground">计划年度 *<input type="number" value={year} onChange={(e) => setYear(Number(e.target.value))} className={inputClass} /></label><label className="text-xs text-muted-foreground">计划周期 *<select value={quarter} onChange={(e) => setQuarter(Number(e.target.value))} className={inputClass}>{[1, 2, 3, 4].map((q) => <option key={q} value={q}>Q{q}（{q * 3 - 2}-{q * 3}月）</option>)}</select></label></div>
    <section className="space-y-3"><div className="flex items-end justify-between"><div><h2 className="font-semibold text-white">A. 季度产品目标看板</h2><p className="text-xs text-muted-foreground">按月拆解季度目标，状态与达成率由组长维护。</p></div><button type="button" onClick={() => setGoals([...goals, blankGoal()])} className="rounded-lg border border-emerald-500/40 px-3 py-2 text-xs text-emerald-300"><Plus className="mr-1 inline h-3.5 w-3.5" />新增目标行</button></div>
      <div className="overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[2600px] text-left"><thead className="bg-emerald-800 text-xs text-white"><tr>{["序", "目标域*", "季度目标*", "成功标准*", `M1目标(${months[0]}月)*`, "M1状态*", `M2目标(${months[1]}月)*`, "M2状态*", `M3目标(${months[2]}月)*`, "M3状态*", "当前完成", "达成率", "季度状态", "关键依赖", "备注", "操作"].map((item) => <th key={item} className="px-2 py-3">{item}</th>)}</tr></thead><tbody>{goals.map((goal, index) => <GoalRow key={goal._key} goal={goal} index={index} set={(next) => setGoals(goals.map((row, i) => i === index ? next : row))} moveUp={() => setGoals(move(goals, index, -1))} moveDown={() => setGoals(move(goals, index, 1))} remove={() => setGoals(goals.filter((_, i) => i !== index))} />)}</tbody></table></div></section>
    <section className="space-y-3"><div className="flex items-end justify-between"><div><h2 className="font-semibold text-white">B. 季度交付风险登记册</h2><p className="text-xs text-muted-foreground">识别本季度核心交付风险及应对策略。</p></div><button type="button" onClick={() => setRisks([...risks, blankRisk()])} className="rounded-lg border border-rose-500/40 px-3 py-2 text-xs text-rose-300"><Plus className="mr-1 inline h-3.5 w-3.5" />新增风险行</button></div>
      <div className="overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[1900px]"><thead className="bg-rose-800 text-xs text-white"><tr>{["风险编号", "风险描述*", "影响里程碑", "概率*", "影响*", "综合级*", "触发条件", "应对策略*", "预警节点", "当前状态*", "操作"].map((item) => <th key={item} className="px-2 py-3 text-left">{item}</th>)}</tr></thead><tbody>{risks.map((risk, index) => <RiskRow key={risk._key} risk={risk} index={index} set={(next) => setRisks(risks.map((row, i) => i === index ? next : row))} moveUp={() => setRisks(move(risks, index, -1))} moveDown={() => setRisks(move(risks, index, 1))} remove={() => setRisks(risks.filter((_, i) => i !== index))} />)}</tbody></table></div></section>{actions}</div>;
}

function GoalRow({ goal, index, set, moveUp, moveDown, remove }: { goal: Goal; index: number; set: (goal: Goal) => void; moveUp: () => void; moveDown: () => void; remove: () => void }) {
  const text = (field: keyof Goal) => <textarea value={String(goal[field] ?? "")} onChange={(e) => set({ ...goal, [field]: e.target.value })} className={textAreaClass} />;
  return <tr className="border-t border-border align-top"><td className="px-2 py-2">{index + 1}</td><td className="p-2"><select value={goal.domain ?? ""} onChange={(e) => set({ ...goal, domain: e.target.value as QuarterlyGoalDomain })} className={inputClass}><option value="">请选择</option>{Object.entries(quarterlyGoalDomainLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></td><td className="p-2">{text("quarterlyGoal")}</td><td className="p-2">{text("successCriteria")}</td><td className="p-2">{text("month1Goal")}</td><td className="p-2"><StatusSelect value={goal.month1Status} onChange={(value) => set({ ...goal, month1Status: value })} /></td><td className="p-2">{text("month2Goal")}</td><td className="p-2"><StatusSelect value={goal.month2Status} onChange={(value) => set({ ...goal, month2Status: value })} /></td><td className="p-2">{text("month3Goal")}</td><td className="p-2"><StatusSelect value={goal.month3Status} onChange={(value) => set({ ...goal, month3Status: value })} /></td><td className="p-2">{text("currentCompletion")}</td><td className="p-2"><input type="number" min={0} max={100} value={goal.achievementRate ?? 0} onChange={(e) => set({ ...goal, achievementRate: Number(e.target.value) })} className={inputClass} /></td><td className="p-2"><StatusSelect value={goal.quarterlyStatus} onChange={(value) => set({ ...goal, quarterlyStatus: value })} /></td><td className="p-2">{text("keyDependencies")}</td><td className="p-2">{text("notes")}</td><td className="p-2"><RowActions up={moveUp} down={moveDown} remove={remove} /></td></tr>;
}

function RiskRow({ risk, index, set, moveUp, moveDown, remove }: { risk: Risk; index: number; set: (risk: Risk) => void; moveUp: () => void; moveDown: () => void; remove: () => void }) {
  const text = (field: keyof Risk) => <textarea value={String(risk[field] ?? "")} onChange={(e) => set({ ...risk, [field]: e.target.value })} className={textAreaClass} />;
  return <tr className="border-t border-border align-top"><td className="p-2 text-rose-300">R{index + 1}</td><td className="p-2">{text("riskDescription")}</td><td className="p-2">{text("affectedMilestone")}</td>{(["probability", "impact", "overallLevel"] as const).map((field) => <td key={field} className="p-2"><select value={risk[field] ?? ""} onChange={(e) => set({ ...risk, [field]: e.target.value as PlanRiskLevel })} className={inputClass}>{Object.entries(planRiskLevelLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></td>)}<td className="p-2">{text("triggerCondition")}</td><td className="p-2">{text("responseStrategy")}</td><td className="p-2">{text("warningPoint")}</td><td className="p-2"><select value={risk.status ?? ""} onChange={(e) => set({ ...risk, status: e.target.value as QuarterlyRiskStatus })} className={inputClass}>{Object.entries(quarterlyRiskStatusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></td><td className="p-2"><RowActions up={moveUp} down={moveDown} remove={remove} /></td></tr>;
}

function StatusSelect({ value, onChange }: { value?: PlanTrackingStatus | null; onChange: (value: PlanTrackingStatus) => void }) { return <select value={value ?? ""} onChange={(e) => onChange(e.target.value as PlanTrackingStatus)} className={inputClass}>{Object.entries(planTrackingStatusLabels).map(([option, label]) => <option key={option} value={option}>{label}</option>)}</select>; }
function RowActions({ up, down, remove }: { up: () => void; down: () => void; remove: () => void }) { return <div className="flex gap-1"><button type="button" onClick={up} title="上移"><ArrowUp className="h-4 w-4" /></button><button type="button" onClick={down} title="下移"><ArrowDown className="h-4 w-4" /></button><button type="button" onClick={remove} title="删除" className="text-rose-400"><Trash2 className="h-4 w-4" /></button></div>; }
